-- ========== Magnitude Analysis

-- Find total customer by countries.
	SELECT
	country,
	COUNT(customer_id) as total_customer
	FROM gold.dim_customer
	GROUP BY country
	ORDER BY total_customer DESC;

-- Find total customers by gender.
	SELECT
	gender,
	COUNT(customer_id) AS total_customer
	FROM gold.dim_customer
	GROUP BY gender
	ORDER BY total_customer DESC;

-- Find total products by category.
	SELECT
	category,
	COUNT(product_id) AS total_products
	FROM gold.dim_products
	GROUP BY category
	ORDER BY total_products DESC;

-- What is the average costs in each category?
   SELECT
   category,
   AVG(cost) as avg_cost
   FROM gold.dim_products
   GROUP BY category
   ORDER BY avg_cost DESC;

-- What is the total revenue is generated by each category?
	SELECT
	category,
	SUM(sales_amount) as revenue
	FROM gold.fact_sales
	LEFT JOIN gold.dim_products
	ON gold.fact_sales.product_key = gold.dim_products.product_key
	GROUP BY category
	ORDER BY revenue DESC;

-- Find total revenue is generated by each customer.
    SELECT
	s.customer_key,
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS revenue
	FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_customer AS c
	ON s.customer_key = c.customer_key
	GROUP BY 
	s.customer_key,
	c.first_name,
	c.last_name
	ORDER BY revenue DESC;

-- What is the distribution of sold items across countries?
   SELECT
   c.country,
   SUM(quantity) AS total_sold_item
   FROM gold.fact_sales AS s
   LEFT JOIN gold.dim_customer AS c
   ON s.customer_key = c.customer_key
   GROUP BY c.country
   ORDER BY total_sold_item DESC;
